theme: jekyll-theme-modernist
<!DOCTYPE html><html lang="en"><head>
<meta charset="UTF-8">
<title>Waves of Chennai | wavesofchennai.com</title>
<meta name="viewport" content="width=device-width, initial-scale=1">     
  <style>
	  @import url('https://fonts.googleapis.com/css2?family=Jost:wght@300&display=swap');
  *{
      height: 100%;
      margin: 0;
      padding: 0;
      font-family: "Jost", sans-serif;
  }
	  
	   .disclaimer {
            position:fixed;
            width:100%;
            left:0;
			top: 7px;
            bottom:0;
            }
		.disclaimer p {
              text-align:right;
			font-size: 13px;
			
			padding: 	10px;
			font-family: "Jost", sans-serif;
              }
		  
	  
  
  .contain {
    position: absolute;
    width: 10px;
    height: 25px;
    margin: 0 auto 0;
    -webkit-perspective: 1000;
    -webkit-backface-visibility: hidden;
    background: transparent;
  }
  
  .contain.one{right: 27%;    top: 72.5%;}/* Search*/
  .contain.two{left: 39%; top: 74%;}/*The morning after*/
  .contain.three{left: 57%; top: 68%;}/*Tryst with the sea*/
	  
  .contain.four{ left: 20%; bottom: 24%;}/*Unstable*/
  .contain.five{ right: 19%; top: 70%;}/*Voice out*/
	  
  .pulse-button {
    display: block;
    width: 8px;
    height: 8px;
    font-size: 0;
    border-color: white;
	
    border-radius: 50%;
    background: #154e83;
    cursor: pointer;
    box-shadow: 0 0 0 0 rgba(90, 153, 212, 0.5);
    -webkit-animation: pulse 1.5s infinite;
  }
  
  .pulse-button:hover {
      background: #fa0000;
    -webkit-animation: none;
  }
  
  @-webkit-keyframes pulse {
    0% {
      -moz-transform: scale(0.9);
      -ms-transform: scale(0.9);
      -webkit-transform: scale(0.9);
      transform: scale(0.9);
    }
    70% {
      -moz-transform: scale(1);
      -ms-transform: scale(1);
      -webkit-transform: scale(1);
      transform: scale(1);
      box-shadow: 0 0 0 50px rgba(90, 153, 212, 0);
    }
    100% {
      -moz-transform: scale(0.9);
      -ms-transform: scale(0.9);
      -webkit-transform: scale(0.9);
      transform: scale(0.9);
      box-shadow: 0 0 0 0 rgba(90, 153, 212, 0);
    }
  }
  
  
  /* Applies to all tooltips */
  .tooltip:before,
  .tooltip:after {
    position: absolute;
    content: '';
    opacity: 0;
    transition: all 0.4s ease;
  }
  
  .tooltip:before {
    border-width: 10px 8px 0 8px;
    border-style: solid;
    border-color: red transparent transparent transparent;
    top: -15px;
     transform: translateY(20px);
  }
  
  .tooltip:after {
    content: attr(tooltip);
    width: 150px;
      height: 15px;
      font-size: 12px;
      font-weight: 300;
      top: -38px;
      left: -10px;
      padding: 5px;
    border-radius: 5px;
    letter-spacing: 1px;
    transform: translateY(20px);
   
  }
  
  .tooltip:hover::before,
  .tooltip:hover::after {
    opacity: 1;
    transform: translateY(-2px);
  }
  audio{display: none;}
  
  
  .tooltip__content {
    position: absolute;
    bottom: 3em;
    opacity: 0.8;
    backface-visibility: hidden;
    left: -999px;
    transition: 0s left 0.2s;
  }
  .is-active .tooltip__content {
    left: 100%;
    transition: 0s left 0s;
  }
  .tooltip__content-inner {
    position: relative;
    margin-left: -100%;
    display: block;
    padding: 0.5em 0;
    color: rgba(0, 0, 0, 0.5);
    font-size: 1em;
    border-radius: 6px;
    box-shadow: 0 0 0 1px rgba(0, 0, 0, 0.15), 0 1px 1px rgba(0, 0, 0, 0.1), 0 1px 1px rgba(0, 0, 0, 0.1), 0 2px 10px rgba(0, 0, 0, 0.3), 0 1px 0 rgba(255, 255, 255, 0.3) inset, 0 -1px 0 rgba(0, 0, 0, 0.05) inset;
    background: #154e83;
    opacity: 0;
    -webkit-filter: blur(40px);
    transform: translateY(-80%) perspective(500px) rotateX(-45deg) scale(1.8);
    transition: all 0.2s cubic-bezier(0.49, 0.2, 0.69, 1.61);
    will-change: auto;
    text-align: center;
    /**
     * Tooltip triangle
     */
  }
  .tooltip__content-inner a{ color: white; text-decoration: none;}
  .is-active .tooltip__content-inner {
    color: rgba(0, 0, 0, 0.5);
    opacity: 0.95;
    -webkit-filter: blur(0);
    transform: translateY(0) scale(1);
  }
  .tooltip__content-inner:before, .tooltip__content-inner:after {
    position: absolute;
    left: 50%;
    margin-left: -6px;
    bottom: -6px;
    content: "";
    display: block;
    width: 0;
    height: 0;
    border-left: 6px solid transparent;
    border-right: 6px solid transparent;
    border-top: 6px solid #154e83;
  }
  .tooltip__content-inner:after {
    bottom: -5px;
    border-top-color: #154e83;
  }
  #popUpFrame{
        display:none;position: absolute;left: 2%;
        top: 4%;margin: 0;padding: 0; width: 96%; height: 92%;z-index: 9;
  }
  #popUpFrame .close {
    position: absolute;
    top: -30px;
    right: -5px;
    transition: all 200ms;
    font-size: 40px;
    font-weight: bold;
    text-decoration: none;
    color: #fff;
  }
  div a img[alt="www.000webhost.com"], .deviceCheck{display: none;}

.bgimg{
      background: url("https://i.postimg.cc/bN216wVq/home-BG.jpg") no-repeat center center/cover;
      /* background: url("image/home-BG.jpg") no-repeat center center/cover; */
		/* <!--"https://unsplash.com/photos/s_vsDWVC8m8" --> */
      height: 100vh;
  }

  a.aboutus{
    text-decoration: none;
    color: white;
    position: absolute;
    font-size: 25px;
    z-index: 5;
    left: 10px;
    top: 10px;height: auto;
}
a.aboutus img{    width: 30px;vertical-align: bottom; background-color: skyblue}
	  
	 
  </style>
	
	 
	  <style>
.alert {
  padding: 	10px;
  background-color: #f44336;
  color: white;
  opacity: 1;
  transition: opacity 0.6s;
  margin-bottom: 15px;
	
	position:fixed;
	height: 35px;
    top: 200px; 
    left: 0px; 
    width: 25%;
    z-index:9999; 
    border-radius:0px
}

.alert.success {background-color: #04AA6D;}
.alert.info {background-color: #2196F3;}
.alert.warning {background-color: #ff9800;}

.closebtn {
  margin-left: 2px;
  color: white;
  font-weight: bold;
  float: right;
  font-size: 22px;
  line-height: 20px;
  cursor: pointer;
  transition: 0.3s;
}

.closebtn:hover {
  color: black;
}
		  


		  
		  
/* working--------------------------------------------------------*/	

	  
		  
/* Portrait GIF animation */
@media only screen 
  and (orientation: portrait) { 
    div.deviceCheck{
        background: #000000 url("image/rotate11.gif") no-repeat center center;
        width: 100%;
        position: fixed;
        top: 0;bottom: 0;
        z-index: 9;
        color: #fff;
        text-align: center;
        overflow: hidden;
        font-size: 2em;
        flex-wrap: wrap;
        align-content: start;
        /*background-size: contain; */
		  background-size: 75%;
      font-size: 0;
      display: block;
    }
}		  
		  
/* Android oled Landscape */
@media only screen 
  and (min-device-width: 360px) 
  and (max-device-width: 812px) 
  and (-webkit-min-device-pixel-ratio: 4)
  and (orientation: landscape) { 
	  
	  .bestView{display: none;}
	  
    .contain.one{ top: 86%;border: 0px solid blue;}/* Search*/
    .contain.two{ top: 85%;}/*The morning after*/
    .contain.three{ top: 82%;}/*Tryst with the sea*/
    .contain.four{ bottom: 8%;}/*Unstable*/
    .contain.five{ top: 85%;}/*Voice out*/

}	
		  
		  
		  

/* Android amoled, and galaxy smart phones Landscape */
@media only screen 
and (min-device-width: 759px) 
and (max-device-width: 1024px)
and (orientation: landscape){
    .bestView{display: none;}
	  
    .contain.one{ top: 9%;border: 0px solid #000000}/* Search*/
    .contain.two{ top: 87%;left: 41%}/*The morning after*/
    .contain.three{ top: 82%;}/*Tryst with the sea*/
    .contain.four{ top: 85%;}/*Unstable*/
    .contain.five{ top: 82%;right: 18%}/*Voice out*/
		
	  
}

 
/* iPad Lanscape only */
body.iPad .contain.one{ top: 70%;right:25%; border: 0px solid #2196F3 !important}/* Search*/
body.iPad .contain.two{ top: 70%;}/*The morning after*/
body.iPad .contain.three{ top: 66%;}/*Tryst with the sea*/
body.iPad .contain.four{ top: 70%; left: 17%}/*Unstable*/
body.iPad .contain.five{ top: 68%; right: 15%}/*Voice out*/
		  

		  
/* working--------------------------------------------------------*/		  
		  
/* iphone-11-pro-max   Landscape */
@media only screen and (min-width: 1896px) and (orientation: landscape) 
{ 
	
	/* Your Styles... */ 
	.bestView{display: none;}

	.contain.one{ top: 86%;border: 10px solid #000000}/* Search*/
    .contain.two{ top: 87%;left: 41%}/*The morning after*/
    .contain.three{ top: 82%;}/*Tryst with the sea*/
    .contain.four{ top: 85%;}/*Unstable*/
    .contain.five{ top: 82%;right: 18%}/*Voice out*/	  
		  
 }		  
		

/* iphone-11-pro-max   Landscape */		  
		  
@media only screen and (device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 2)and (orientation: landscape) 
			  
  { 
		  
		  
	/* Your Styles... */ 
	.bestView{display: none;}

	.contain.one{ top: 86%;border: 0px solid #6b0ef6}/* Search*/
    .contain.two{ top: 87%;left: 41%}/*The morning after*/
    .contain.three{ top: 82%;}/*Tryst with the sea*/
    .contain.four{ top: 85%;}/*Unstable*/
    .contain.five{ top: 82%;right: 18%}/*Voice out*/	
		  
		  
  }
			  
@media only screen 
	
and (max-device-width: 1024px)
	
	and (orientation: landscape)
{ 
	/* Your Styles... */
		  
 	.bestView{display: none;}

	/*.contain.one{ top: 1%;border: 10px solid #660066}/* Search*/
    /* .contain.two{ top: 1%;left: 41%}/*The morning after*/
    /*.contain.three{ top: 2%;}/*Tryst with the sea*/
    /* .contain.four{ top: 5%;}/*Unstable*/
    /*.contain.five{ top: 2%;right: 18%}/*Voice out*/	  
	
	
	.contain.one{ top: 79%;right: 17px border: 0px solid #ffcc00}/* Search*/
    .contain.two{ top: 79%;left: 39%}/*The morning after*/
    .contain.three{ top: 77%;}/*Tryst with the sea*/
    .contain.four{ top: 80%;}/*Unstable*/
    .contain.five{ top: 78%;right: 18%}/*Voice out*/
		  
		  
 }
		  
		  
		  
		  
		  
</style>
  </head>
  
<body translate="no" class="container">
	
    <div class="bgimg"></div>
    <a class="aboutus" href="about.html"><img src="https://img.icons8.com/ios-filled/50/ffffff/info.png"/></a>
	<div class="disclaimer">
		<p>	<img src="https://img.icons8.com/ios/50/ffffff/headphones.png" style="width: 30px;height: 30px" align="middle"/>&nbsp;<b>Use Headphones</b> </p>
    </div>

	
	
	 
    <div class='contain one'>
        <span class='pulse-button' style="border-style: double; border-width:thin; border-color: #fff">
            <audio controls id="s1">
                <source src="audio/Searching.mp3" type="audio/mpeg">
                Your browser does not support the audio element.
            </audio>
        </span>
        <span class="tooltip__content" style="width: 80px">
           <span class="tooltip__content-inner">
                <a href="#" data-video="https://www.youtube.com/embed/uh6TDTrK-dc?controls=0&showinfo=0&rel=0&autoplay=1&loop=1&mute=0&playlist=uh6TDTrK-dc">Searching ▶️</a>
            </span>
        </span>
    </div>
    <div class='contain two'>
        <span class='pulse-button' style="border-style: double; border-width: thin; border-color: #fff">
            <audio controls id="s2">
                <source src="audio/TheMorningafter.mp3" type="audio/mpeg">
                Your browser does not support the audio element.
            </audio>
        </span>
        <span class="tooltip__content" style="width: 90px">
            <span class="tooltip__content-inner">
                <a href="#" data-video="https://www.youtube.com/embed/jcPxPPppVos?controls=0&showinfo=0&rel=0&autoplay=1&loop=1&mute=0&playlist=jcPxPPppVos">Morning After ▶️</a>
            </span>
        </span>
    </div>
    <div class='contain three'>
        <span class='pulse-button' style="border-style: double; border-width: thin; border-color: #fff">
            <audio controls id="s3">
                <source src="audio/TrystWithTheSea.mp3" type="audio/mpeg">
                Your browser does not support the audio element.
            </audio>
        </span>
        <span class="tooltip__content" style="width: 100px">
            <span class="tooltip__content-inner">
                <a href="#" data-video="https://www.youtube.com/embed/4Q7I_78cQPk?controls=0&showinfo=0&rel=0&autoplay=1&loop=1&mute=0&playlist=4Q7I_78cQPk">Tryst With The Sea ▶️</a>
            </span>
        </span>
    </div>
  
    <div class='contain four'>
        <span class='pulse-button' style="border-style: double; border-width: thin; border-color: #fff">
            <audio controls id="s4">
                <source src="audio/Unstable.mp3" type="audio/mpeg">
                Your browser does not support the audio element.
            </audio>
        </span>
        <span class="tooltip__content" style="width: 60px">
            <span class="tooltip__content-inner">
                <a href="#" data-video="https://www.youtube.com/embed/kU5RaGFK5f4?controls=0&showinfo=0&rel=0&autoplay=1&loop=1&mute=0&playlist=kU5RaGFK5f4">Unstable ▶️</a>
            </span>
        </span>
    </div>
  
    <div class='contain five'>
        <span class='pulse-button' style="border-style: double; border-width: thin; border-color: #fff">
            <audio controls id="s5">
                <source src="audio/VoiceOut.mp3" type="audio/mpeg">
                Your browser does not support the audio element.
            </audio>
        </span>
        <span class="tooltip__content" style="width: 60px">
            <span class="tooltip__content-inner">
                <a href="#" data-video="https://www.youtube.com/embed/MSyzZS9QDmw?modestbranding=1&controls=0&showinfo=0&rel=0&autoplay=1&loop=1&mute=0&playlist=MSyzZS9QDmw">Voice Out ▶️</a>
            </span>
        </span>
    </div>
  
  <!--audio controls id="myAudio">
      <source src="https://www.friendstamilmp3.in/songs2/Remix%20Collections/A.R.Rahman%20Songs%20Remix/Kurukku%20Sivanthavaley%20-%20Mudhalvan.mp3" type="audio/mpeg">
      Your browser does not support the audio element.
  </audio-->
  
  <div id="popUpFrame">
      <a class="close" href="#">&times;</a>
      <iframe id="youtube_player" class="yt_player_iframe" height="100%" id="video" width="100%" src="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="true" allowscriptaccess="always" style="opacity: 1;"></iframe>    
  </div>

  <div class="deviceCheck"> <!--Rotate your phone to landscape mode for best view.--></div> 
  
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script id="rendered-js">
"use strict";
$(document).ready(function () {    
      function aReset() {
          $('audio').each(function(){
              this.pause(); // Stop playing
              this.currentTime = 0; // Reset time
          }); 
      }
  
      $("div.contain span.pulse-button").click(function (e) {
          aReset();$("div.contain").removeClass('is-active');
          var songId = $(this).find("audio").attr("id");
          $(this).parent().addClass('is-active');
          document.getElementById(songId).play();
      });
  
      $("div.contain a").click(function (e) {
          e.preventDefault();
          $("#youtube_player").attr("src", $(this).data('video'));
          
          aReset();
          $("div.contain").removeClass('is-active');
          $('#popUpFrame').show();
      });
      
  
      $(".close").click(function (e) {
          $("#popUpFrame").hide(); $("#youtube_player").attr("src","");
          $('iframe.yt_player_iframe').each(function(){
              this.contentWindow.postMessage('{"event":"command","func":"stopVideo","args":""}', '*')
          });
      });
      
      var is_iPad = navigator.userAgent.match(/iPad/i) != null;
      is_iPad ? $('body').addClass('iPad'): '';
  });
  </script>
